name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'docker-compose.yml'
      - 'Makefile'
      - '.github/workflows/**'
      - '*dockerfile'
      - 'app/dockerfile'
      - 'modules/**'
      - '**.tf'
jobs:
  image_build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
      AWS_ACCOUNT_NUMBER:  ${{ secrets.AWS_ACCOUNT_NUMBER }} 
      REGION:  ${{ secrets.REGION }} 
      REPO_PARAMETER_NAME:  ${{ secrets.REPO_PARAMETER_NAME }}   
      SLACK_WEBHOOK:  ${{ secrets.SLACK_WEBHOOK }}  
    steps:
    - uses: actions/checkout@v2
    - name: Notify_Slack
      run: ./scripts/slack_notify.sh "Building weather app image"
    - name: Container_Build
      run: make build
    - name: Container_Push
      run: make push
    - name: Notify_Slack
      run: ./scripts/slack_notify.sh "Pushed image to ECR"
